env: "local"
storage_path: "./storage/storage.db"
connection_string: "host=localhost port=5432 user=postgres password=230704 dbname=postgres sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s #Время на чтение запроса и отправку
  idle_timeout: 60s #Время жизни соединения с клиентом