stages:
  - test

test-job:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build url-shortener
    - docker compose -f docker/test/docker-compose.yml --abort-on-container-exit